### PR TITLE
Fatih

### PR DESCRIPTION
**Pull request by sekerfati**
some codes added to the master

### CODE REVIEW

**Comment by benb003** [comment]
good

**Comment by CanerEsiyok** [comment]
I reviewed the changes that you had made.

**Review by CanerEsiyok — APPROVED** [review]

**Review by benb003 — APPROVED** [review]

**Review by benb003 — APPROVED** [review]
good

**Review by CanerEsiyok — APPROVED** [review]

**Review by msaitture — APPROVED** [review]
sait

**Pull request merged**
